export const T = {
  CHANGE_MODAL_VISIBLE: "CHANGE_MODAL_VISIBLE",
  ADD_TEAM_CARD: "ADD_TEAM_CARD",
  GET_TEAM_CARDS: "GET_TEAM_CARDS",
  INSERT_TEAM_CARD_DATA: "INSERT_TEAM_CARD_DATA",
  CHECK_UPDATE_PASSWORD: "CHECK_UPDATE_PASSWORD",
  UPDATE_TEAM_CARD: "UPDATE_TEAM_CARD"
};
